In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stas

In [2]:
from src.utils.snapshot import latest_snapshot, processed_dir
from src.analytics.demografia import Demografia

In [3]:
SNAPSHOT = latest_snapshot()
df = pd.read_parquet(processed_dir(SNAPSHOT) / 'fide_players_all.parquet')

In [4]:
FED = "NCA"

df_federacion = df[df['country'] == FED]
df_federacion.info()

<class 'pandas.DataFrame'>
Index: 620 entries, 7394 to 774758
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   fideid          620 non-null    str
 1   name            620 non-null    str
 2   country         620 non-null    str
 3   sex             620 non-null    str
 4   title           620 non-null    category
 5   o_title         620 non-null    str
 6   rating          430 non-null    Int16
 7   games           620 non-null    int16
 8   rapid_rating    322 non-null    Int16
 9   rapid_games     620 non-null    int16
 10  blitz_rating    414 non-null    Int16
 11  blitz_games     620 non-null    int16
 12  birthday        620 non-null    int16
 13  snapshot_date   620 non-null    object
 14  total_games     620 non-null    int16
 15  activo_mes      620 non-null    bool
 16  activo_fide     620 non-null    bool
 17  edad            620 non-null    int64
 18  categoria       620 non-null    category
 19  player_profile  620 non-null    category
dtypes: Int16(3), bool(2), category(3), int16(5), int64(1), object(1), str(5)
memory usage: 79.4+ KB

In [ ]:
columnas = ["rating","rapid_rating", "blitz_games", "edad","birthday"]
df_federacion[columnas].describe().T

,count,mean,std,min,25%,50%,75%,max
rating,430.0,1727.348837,180.39887,1402.0,1594.0,1705.0,1836.0,2335.0
games,620.0,0.153226,1.112743,0.0,0.0,0.0,0.0,10.0
rapid_rating,322.0,1711.549689,174.505297,1400.0,1588.25,1695.5,1816.25,2260.0
rapid_games,620.0,0.017742,0.323563,0.0,0.0,0.0,0.0,7.0
blitz_rating,414.0,1702.797101,166.130531,1420.0,1584.0,1671.0,1790.75,2280.0
blitz_games,620.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
birthday,620.0,1995.25,15.50383,1931.0,1987.0,2000.0,2007.0,2018.0
total_games,620.0,0.170968,1.184088,0.0,0.0,0.0,0.0,10.0
edad,620.0,30.75,15.50383,8.0,19.0,26.0,39.0,95.0

In [6]:
fed = Demografia(df, FED)

df_resumen = fed.kpis_demograficos()
df_resumen

                   cantidad  porcentaje
indicador
registrados             620       100.0
hombres                 532        85.8
mujeres                  88        14.2
juveniles               177        28.5
adultos                 443        71.5
mujeres_juveniles        48        27.1
mujeres_adultas          40         9.0
titulados                31         5.0
sin_titulo              589        95.0

In [7]:
df_resumen_categorias = fed.resumen_demografico()
df_resumen_categorias

  categoria  registrados    M   F  pct_F  edad_mediana
0     Sub 8            1    0   1  100.0           8.0
1    Sub 10            4    3   1   25.0           9.0
2    Sub 12           14    9   5   35.7          12.0
3    Sub 14           30   20  10   33.3          14.0
4    Sub 16           36   27   9   25.0          16.0
5    Sub 18           45   33  12   26.7          18.0
6    Sub 20           47   37  10   21.3          19.0
7  Absoluta          443  403  40    9.0          31.0