In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stas

In [2]:
from src.utils.snapshot import latest_snapshot, processed_dir
from src.analytics.demografia import Demografia

In [4]:
SNAPSHOT = latest_snapshot()
df = pd.read_parquet(processed_dir(SNAPSHOT) / 'fide_players_all.parquet')
df_nicaragua= df[df['country'] == "NCA"]
df_nicaragua.info()

<class 'pandas.DataFrame'>
Index: 620 entries, 7394 to 774758
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   fideid          620 non-null    str
 1   name            620 non-null    str
 2   country         620 non-null    str
 3   sex             620 non-null    str
 4   title           620 non-null    category
 5   o_title         620 non-null    str
 6   rating          430 non-null    Int16
 7   games           620 non-null    int16
 8   rapid_rating    322 non-null    Int16
 9   rapid_games     620 non-null    int16
 10  blitz_rating    414 non-null    Int16
 11  blitz_games     620 non-null    int16
 12  birthday        620 non-null    int16
 13  snapshot_date   620 non-null    object
 14  total_games     620 non-null    int16
 15  activo_mes      620 non-null    bool
 16  activo_fide     620 non-null    bool
 17  edad            620 non-null    int64
 18  categoria       620 non-null    category
 19  player_profile  620 non-null    category
dtypes: Int16(3), bool(2), category(3), int16(5), int64(1), object(1), str(5)
memory usage: 79.4+ KB

In [6]:
df_nicaragua.describe()

,rating,games,rapid_rating,rapid_games,blitz_rating,blitz_games,birthday,total_games,edad
count,430.0,620.000000,322.0,620.000000,414.0,620.0,620.00000,620.000000,620.00000
mean,1727.348837,0.153226,1711.549689,0.017742,1702.797101,0.0,1995.25000,0.170968,30.75000
std,180.39887,1.112743,174.505297,0.323563,166.130531,0.0,15.50383,1.184088,15.50383
min,1402.0,0.000000,1400.0,0.000000,1420.0,0.0,1931.00000,0.000000,8.00000
25%,1594.0,0.000000,1588.25,0.000000,1584.0,0.0,1987.00000,0.000000,19.00000
50%,1705.0,0.000000,1695.5,0.000000,1671.0,0.0,2000.00000,0.000000,26.00000
75%,1836.0,0.000000,1816.25,0.000000,1790.75,0.0,2007.00000,0.000000,39.00000
max,2335.0,10.000000,2260.0,7.000000,2280.0,0.0,2018.00000,10.000000,95.00000

In [7]:
fed = Demografia(df, "NCA")
resumen = fed.kpis_demograficos()

df_resumen = fed.kpis_demograficos()
df_resumen

                   cantidad  porcentaje
indicador
registrados             620       100.0
hombres                 532        85.8
mujeres                  88        14.2
juveniles               177        28.5
adultos                 443        71.5
mujeres_juveniles        48        27.1
mujeres_adultas          40         9.0
titulados                31         5.0
sin_titulo              589        95.0