In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stas

In [2]:
from src.utils.snapshot import latest_snapshot, processed_dir
from src.analytics.demografia import Demografia

In [3]:
SNAPSHOT = latest_snapshot()
df = pd.read_parquet(processed_dir(SNAPSHOT) / 'fide_players_all.parquet')

In [4]:
FED = "RUS"

df_federacion = df[df['country'] == FED]
df_federacion.info()

<class 'pandas.DataFrame'>
Index: 71146 entries, 11 to 782819
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   fideid          71146 non-null  str
 1   name            71146 non-null  str
 2   country         71146 non-null  str
 3   sex             71146 non-null  str
 4   title           71146 non-null  category
 5   o_title         71146 non-null  str
 6   rating          43534 non-null  Int16
 7   games           71146 non-null  int16
 8   rapid_rating    50316 non-null  Int16
 9   rapid_games     71146 non-null  int16
 10  blitz_rating    37245 non-null  Int16
 11  blitz_games     71146 non-null  int16
 12  birthday        71146 non-null  int16
 13  snapshot_date   71146 non-null  object
 14  total_games     71146 non-null  int16
 15  activo_mes      71146 non-null  bool
 16  activo_fide     71146 non-null  bool
 17  edad            71146 non-null  int64
 18  categoria       71146 non-null  category
 19  player_profile  71146 non-null  category
dtypes: Int16(3), bool(2), category(3), int16(5), int64(1), object(1), str(5)
memory usage: 8.1+ MB

In [ ]:
columnas = ["rating","rapid_rating", "blitz_games", "edad","birthday"]
df_federacion[columnas].describe().T

,count,mean,std,min,25%,50%,75%,max
rating,43534.0,1776.409427,255.503568,1400.0,1557.0,1743.0,1955.0,2812.0
games,71146.0,0.059919,0.692901,0.0,0.0,0.0,0.0,18.0
rapid_rating,50316.0,1700.957727,213.599579,1400.0,1528.0,1662.0,1839.0,2783.0
rapid_games,71146.0,0.369466,2.123088,0.0,0.0,0.0,0.0,65.0
blitz_rating,37245.0,1727.599141,218.354641,1400.0,1550.0,1696.0,1871.0,2783.0
blitz_games,71146.0,0.348888,2.637357,0.0,0.0,0.0,0.0,142.0
birthday,71146.0,1991.614103,22.007006,1920.0,1979.0,2001.0,2009.0,2020.0
total_games,71146.0,0.778273,4.292944,0.0,0.0,0.0,0.0,192.0
edad,71146.0,34.385897,22.007006,6.0,17.0,25.0,47.0,106.0

In [6]:
fed = Demografia(df, FED)

df_resumen = fed.kpis_demograficos()
df_resumen

                   cantidad  porcentaje
indicador
registrados           71014      100.00
hombres               60153       84.70
mujeres               10861       15.30
juveniles             26571       37.40
adultos               44443       62.60
mujeres_juveniles      5252       19.80
mujeres_adultas        5609       12.60
titulados              2575        3.63
sin_titulo            68439       96.37

In [7]:
df_resumen_categorias = fed.resumen_demografico()
df_resumen_categorias

  categoria  registrados      M     F  pct_F  edad_mediana
0     Sub 8          258    211    47   18.2           8.0
1    Sub 10         1498   1229   269   18.0          10.0
2    Sub 12         3255   2590   665   20.4          12.0
3    Sub 14         4583   3638   945   20.6          14.0
4    Sub 16         5430   4364  1066   19.6          16.0
5    Sub 18         6032   4832  1200   19.9          17.0
6    Sub 20         5515   4455  1060   19.2          19.0
7  Absoluta        44443  38834  5609   12.6          40.0