In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy.stats as stas

In [4]:
from src.utils.snapshot import latest_snapshot, processed_dir
from src.analytics.demografia import DemografiaFederacion

In [5]:
SNAPSHOT = latest_snapshot()
df = pd.read_parquet(processed_dir(SNAPSHOT) / 'fide_players_all.parquet')

In [6]:
FED = "VEN"

df_federacion = df[df['country'] == FED]
df_federacion.info()

<class 'pandas.DataFrame'>
Index: 5503 entries, 1738 to 782211
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   fideid          5503 non-null   str
 1   name            5503 non-null   str
 2   country         5503 non-null   str
 3   sex             5503 non-null   str
 4   title           5503 non-null   category
 5   o_title         5503 non-null   str
 6   rating          3384 non-null   Int16
 7   games           5503 non-null   int16
 8   rapid_rating    3943 non-null   Int16
 9   rapid_games     5503 non-null   int16
 10  blitz_rating    3771 non-null   Int16
 11  blitz_games     5503 non-null   int16
 12  birthday        5503 non-null   int16
 13  snapshot_date   5503 non-null   object
 14  total_games     5503 non-null   int16
 15  activo_mes      5503 non-null   bool
 16  activo_fide     5503 non-null   bool
 17  edad            5503 non-null   int64
 18  categoria       5503 non-null   category
 19  player_profile  5503 non-null   category
dtypes: Int16(3), bool(2), category(3), int16(5), int64(1), object(1), str(5)
memory usage: 699.9+ KB

In [7]:
df_federacion.describe().T

,count,mean,std,min,25%,50%,75%,max
rating,3384.0,1713.287234,197.279272,1401.0,1552.0,1694.0,1846.0,2454.0
games,5503.0,0.404325,1.933621,0.0,0.0,0.0,0.0,26.0
rapid_rating,3943.0,1695.787218,184.311693,1400.0,1547.0,1682.0,1824.0,2414.0
rapid_games,5503.0,0.355442,1.763907,0.0,0.0,0.0,0.0,54.0
blitz_rating,3771.0,1706.332538,185.479228,1400.0,1554.0,1694.0,1837.0,2455.0
blitz_games,5503.0,0.204797,1.383301,0.0,0.0,0.0,0.0,50.0
birthday,5503.0,1993.078139,17.317656,1929.0,1981.0,1998.0,2007.0,2021.0
total_games,5503.0,0.964565,3.660186,0.0,0.0,0.0,0.0,104.0
edad,5503.0,32.921861,17.317656,5.0,19.0,28.0,45.0,97.0

In [8]:
fed = DemografiaFederacion(df, FED)

df_resumen = fed.kpis_demograficos()
df_resumen

                   cantidad  porcentaje
indicador
registrados            5503      100.00
hombres                4818       87.55
mujeres                 685       12.45
juveniles              1684       30.60
adultos                3819       69.40
mujeres_juveniles       333       19.77
mujeres_adultas         352        9.22
titulados               183        3.33
sin_titulo             5320       96.67

In [9]:
df_resumen_categorias = fed.resumen_demografico()
df_resumen_categorias

  categoria  registrados     M    F  pct_F  edad_mediana
0     Sub 8           19    16    3   15.8           8.0
1    Sub 10           70    51   19   27.1          10.0
2    Sub 12          177   129   48   27.1          12.0
3    Sub 14          308   240   68   22.1          14.0
4    Sub 16          344   272   72   20.9          15.0
5    Sub 18          351   288   63   17.9          18.0
6    Sub 20          415   355   60   14.5          20.0
7  Absoluta         3819  3467  352    9.2          38.0

In [10]:
df_resumen_perfiles = fed.resumen_perfiles()
df_resumen_perfiles

         player_profile  jugadores   pct
0              completo       2194  39.9
1  especialista_clasico        529   9.6
2   especialista_rapido        844  15.3
3    especialista_blitz        729  13.2
4        clasico_rapido        359   6.5
5         clasico_blitz        302   5.5
6          rapido_blitz        546   9.9