In [ ]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df = pd.read_parquet('../data/marts/mart_venezuela.parquet')
df.head()

,fideid,name,country,sex,title,w_title,o_title,rating,rapid_rating,blitz_rating,...,flag,es_activo,edad,categoria,percentil_rating_local,z_score_rating_local,percentil_rapid_rating_local,z_score_rapid_rating_local,percentil_blitz_rating_local,z_score_blitz_rating_local
0,23908467,"Abdel Kayed, Yasin",VEN,M,nt,nt,nt,NaN,1680.0,1739.0,...,,True,14,Sub 16,NaN,NaN,0.839357,0.993671,0.900990,1.334410
1,3988457,"Abello Gomez, Luis Enrique",VEN,M,nt,nt,nt,NaN,1529.0,1635.0,...,,True,20,Absoluta,NaN,NaN,0.108149,-0.815900,0.317460,-0.326848
2,3909468,"Abiad Parra, Victor",VEN,M,CM,nt,nt,1953.0,1872.0,1887.0,...,,True,32,Absoluta,0.696552,0.418831,0.790937,0.619247,0.808768,0.653696
3,23922443,"Abraham Hernandez, Fabrizio Valentino",VEN,M,nt,nt,nt,1530.0,1562.0,1536.0,...,,True,12,Sub 14,0.598214,0.134259,0.753012,0.473795,0.622378,0.166667
4,23922451,"Abraham Hernandez, Maxximo Saiann",VEN,M,nt,nt,nt,1481.0,1524.0,1535.0,...,,True,13,Sub 14,0.370536,-0.319444,0.587349,0.155136,0.611888,0.159420

In [12]:
df_femenino = df[df["sex"] == "F"]

filtro = df_femenino[df_femenino["edad"] >= 16]

filtro[filtro["edad"] <= 18].head(20)

,fideid,name,country,sex,title,w_title,o_title,rating,rapid_rating,blitz_rating,...,flag,es_activo,edad,categoria,percentil_rating_local,z_score_rating_local,percentil_rapid_rating_local,z_score_rapid_rating_local,percentil_blitz_rating_local,z_score_blitz_rating_local
18,3991113,"Acevedo Mendez, Andry Krisbell",VEN,F,nt,nt,nt,NaN,1616.0,1510.0,...,w,True,17,Sub 18,NaN,NaN,0.640704,0.259542,0.313830,-0.310174
23,3935680,"Acosta Camarillo, Neyslin Sophia",VEN,F,nt,nt,nt,1645.0,1535.0,1582.0,...,w,True,17,Sub 18,0.674603,0.374317,0.404523,-0.152672,0.531915,0.047146
60,3972402,"Alcharani Larez, Kamila del Valle",VEN,F,nt,nt,nt,NaN,NaN,1608.0,...,w,True,17,Sub 18,NaN,NaN,NaN,NaN,0.603723,0.176179
73,3967603,"Alvarado Salcedo, Melianny Andreina",VEN,F,nt,nt,nt,NaN,NaN,1502.0,...,w,True,18,Sub 20,NaN,NaN,NaN,NaN,0.270115,-0.410842
131,23923318,"Aparicio Alvarado, Estefany Sarai",VEN,F,nt,nt,nt,1545.0,1690.0,1458.0,...,w,True,16,Sub 18,0.365079,-0.172131,0.788945,0.636132,0.212766,-0.568238
169,23925949,"Arevalo Salazar, Daniela Marcela",VEN,F,nt,nt,nt,1411.0,1465.0,1430.0,...,w,True,17,Sub 18,0.007937,-0.904372,0.218593,-0.508906,0.074468,-0.707196
203,3979407,"Azuaje Alvarez, Andrea Shantalith",VEN,F,nt,nt,nt,NaN,1470.0,NaN,...,w,True,18,Sub 20,NaN,NaN,0.173184,-0.586207,NaN,NaN
273,3999653,"Berra Cadena, Carla Sofia",VEN,F,nt,nt,nt,NaN,1439.0,1429.0,...,w,True,16,Sub 18,NaN,NaN,0.125628,-0.641221,0.069149,-0.712159
310,3968022,"Bonilla Gonzalez, Gabriela Alejandra",VEN,F,nt,nt,nt,NaN,1441.0,NaN,...,w,True,18,Sub 20,NaN,NaN,0.114525,-0.729064,NaN,NaN
349,3951529,"Brito Marquez, Sophia Valentina",VEN,F,nt,nt,nt,1795.0,1681.0,1847.0,...,w,True,18,Sub 20,0.807229,0.619647,0.717877,0.453202,0.908046,1.557775
381,3955516,"Cabello Hurtado, Ivana Carolina",VEN,F,nt,nt,nt,NaN,1440.0,1404.0,...,w,True,18,Sub 20,NaN,NaN,0.106145,-0.733990,0.008621,-0.970043
402,23907207,"Caicedo Agelvis, Fabiola Valentina",VEN,F,nt,nt,nt,NaN,1430.0,1444.0,...,w,True,16,Sub 18,NaN,NaN,0.077889,-0.687023,0.146277,-0.637717
420,3999688,"Calzadilla Brito, Deubelys Crismar",VEN,F,nt,nt,nt,NaN,1466.0,NaN,...,w,True,16,Sub 18,NaN,NaN,0.226131,-0.503817,NaN,NaN
480,3994503,"Carrero Campos, Christmar Sarai",VEN,F,nt,nt,nt,NaN,1444.0,1432.0,...,w,True,16,Sub 18,NaN,NaN,0.148241,-0.615776,0.085106,-0.697270
487,23918039,"Carrillo Blanco, Fabiana Willianis",VEN,F,nt,nt,nt,NaN,1560.0,NaN,...,w,True,16,Sub 18,NaN,NaN,0.479899,-0.025445,NaN,NaN
650,3957411,"Contreras Guzman, Dayana Estefania",VEN,F,nt,nt,nt,NaN,NaN,1465.0,...,w,True,17,Sub 18,NaN,NaN,NaN,NaN,0.218085,-0.533499
682,3990990,"Cotis Guerra, Georgelys Valeria de los Angeles",VEN,F,nt,nt,nt,1472.0,NaN,NaN,...,w,True,17,Sub 18,0.095238,-0.571038,NaN,NaN,NaN,NaN
747,23919019,"Diaz Barreto, Emily Andrea",VEN,F,nt,nt,nt,NaN,NaN,1626.0,...,w,True,18,Sub 20,NaN,NaN,NaN,NaN,0.672414,0.296719
750,23915595,"Diaz Blanco, Isabela Teresa",VEN,F,nt,nt,nt,NaN,1680.0,NaN,...,w,True,17,Sub 18,NaN,NaN,0.758794,0.585242,NaN,NaN
756,23906030,"Diaz Galindez, Daniela Lourdes",VEN,F,nt,nt,nt,1579.0,NaN,1424.0,...,w,True,16,Sub 18,0.515873,0.013661,NaN,NaN,0.053191,-0.736973